version: '3.4'

services:
  nicolasplaisant.calculajuros.calculadora.api:
    image: nicolasplaisantcalculajuroscalculadoraapi:dev
    container_name: NicolasPlaisant.CalculaJuros.Calculadora.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "NicolasPlaisant.CalculaJuros.Calculadora.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\nsbt\dev\calcula-juros\NicolasPlaisant.CalculaJuros.Calculadora.API:/app
      - C:\Users\nsbt\dev\calcula-juros:/src
      - C:\Users\nsbt\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\nsbt\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/netcoreapp3.1/NicolasPlaisant.CalculaJuros.Calculadora.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  nicolasplaisant.calculajuros.retornataxa.api:
    image: nicolasplaisantcalculajurosretornataxaapi:dev
    container_name: NicolasPlaisant.CalculaJuros.RetornaTaxa.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "NicolasPlaisant.CalculaJuros.RetornaTaxa.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\nsbt\dev\calcula-juros\NicolasPlaisant.CalculaJuros.RetornaTaxa.API:/app
      - C:\Users\nsbt\dev\calcula-juros:/src
      - C:\Users\nsbt\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\nsbt\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/netcoreapp3.1/NicolasPlaisant.CalculaJuros.RetornaTaxa.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
